# Generated by Django 5.1.4 on 2025-01-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('FINANCE', 'Finance'), ('HR', 'HR')], max_length=10)),
                ('login_email', models.EmailField(max_length=254)),
                ('login_password', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=255)),
                ('authenticated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
