# Generated by Django 5.1.5 on 2025-02-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='unique_message_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
