# Generated by Django 5.1.4 on 2025-05-02 15:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="embedding",
            field=pgvector.django.vector.VectorField(default=None, dimensions=1536),
            preserve_default=False,
        ),
    ]
