# Generated by Django 5.1.5 on 2025-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_unique_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='login_password',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
