# Generated by Django 5.1.5 on 2025-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatsession_login_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='login_password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
