# Generated by Django 5.1.5 on 2025-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatsession_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
